### ISSUE TITLE
[Bug]: this does not work for new clerk UI

### ISSUE THREAD

**Issue by 1pharaxh** [stormynight9/clerk-shadcn-theme#4]
Hi I recently updated clerk to the most recent version and I noticed that the themes don't work correctly perhaps clerk changed a lot of their class names. 
![image](https://github.com/stormynight9/clerk-shadcn-theme/assets/93630550/81e0d116-a2cb-455f-9a7e-29c53e782558)

This is what I see on dark mode 
<img width="1057" alt="image" src="https://github.com/stormynight9/clerk-shadcn-theme/assets/93630550/46d87bd1-6ef2-4729-9be1-ac633bc59d97">

**Comment by stormynight9** [comment]
Hello @1pharaxh. Thanks for bringing this up.

Clerk has recently released a design-revamp that includes breaking styling changes. As a result this theme doesn't work on the new version yet. I'll try updating it as soon as I have time.

**Comment by stormynight9** [comment]
I have updated the code and now it should support the new Clerk UI, please try it out and let me know if there are any issues.
